---
# handlers file for process-exporter
- name: "Start process_exporter"
  become: true
  become_method: sudo
  ansible.builtin.systemd:
    name: process_exporter.service
    enabled: yes
    state: started
    daemon_reload: yes
